// Generate PNG icons from source image using sharp.
// Source: icon_source.png (generated by AI, 1280x960 landscape)
// Output: images/icon16.png, images/icon48.png, images/icon128.png
// The source image has a white margin; we crop to the square purple area first.

const sharp = require('sharp');
const path = require('path');
const fs = require('fs');

const SOURCE = path.join(
  'C:\\Users\\mirek\\.cursor\\projects\\c-Users-mirek-Documents-UdemySubtitles',
  'assets',
  'icon_source.png'
);

const OUT_DIR = path.join(__dirname, 'images');
if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR);

async function run() {
  const meta = await sharp(SOURCE).metadata();
  console.log(`Source: ${meta.width}x${meta.height}`);

  // The generated image is 1280x960 landscape with white background margins.
  // The square purple icon is centred. Crop to a square from the centre.
  const side = Math.min(meta.width, meta.height); // 960
  const left = Math.floor((meta.width - side) / 2);
  const top  = Math.floor((meta.height - side) / 2);

  for (const size of [16, 48, 128]) {
    const outPath = path.join(OUT_DIR, `icon${size}.png`);
    await sharp(SOURCE)
      .extract({ left, top, width: side, height: side })
      .resize(size, size, { kernel: sharp.kernel.lanczos3 })
      .png()
      .toFile(outPath);
    console.log(`  Created ${outPath} (${size}x${size})`);
  }
  console.log('Done.');
}

run().catch(err => { console.error(err); process.exit(1); });
